
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    id: k8gb
    main: ./main.go
    binary: bin/k8gb
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Tag }}
